default: true

# Allow longer lines in Markdown (tables/links/code often exceed 80)
MD013: false

# IMPORTANT: Do NOT require blank lines around headings (your requirement: minimum 0)
MD022: false

# Require a single trailing newline in files (usually aligned with EditorConfig)
MD047: true

# Allow inline HTML (some teams disable; keep enabled for flexibility)
MD033: false

# Code fences should have language identifiers (helps readability, syntax highlight)
MD040: true

# No duplicate headings in a single document (case-insensitive)
MD024:
  siblings_only: true

# Headings should increment by 1 level at a time (avoid skipping like # -> ###)
MD001: true

# Unordered list marker style: use "-" consistently
MD004:
  style: dash

# Ordered list item prefix: "1." style (auto-numbering friendly)
MD029:
  style: one_or_ordered

# Trailing spaces: allow 2 spaces only when used as a hard line break
MD009:
  br_spaces: 2
  strict: true

# Excessive consecutive blank lines are noisy (keep at most 1)
MD012:
  maximum: 1

# Allow emphasis instead of headings? (Teams often dislike bold-as-heading)
# Enable to discourage using **text** as pseudo-heading
MD036: true

# The first line of the file should be a top-level heading
# If you have docs like CHANGELOG with badges/front-matter, consider disabling.
MD041: true

MD060: false
