default:
  image: repo.gabia.com/gabiacloud/temurin:jdk25-ubi9-node24-minimal
  interruptible: true # 동일한 파이프라인에 대해 새로운 파이프라인 작업이 시작되면 기존 파이프라인 작업은 종료됩니다.

stages:
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GIT_DEPTH: "0"

cache:
  key: "${CI_PROJECT_PATH_SLUG}"
  policy: pull-push
  paths:
    - .gradle/caches/
    - .gradle/wrapper/

.run_module_tests:
  script:
    - |
      set -euo pipefail
      module="$MODULE_PATH"
      ./gradlew "${module}:jacocoMergedCoverageReport"

.test_and_integration_artifacts:
  when: always
  reports:
    junit:
      - "**/build/reports/jacoco/merged/jacocoMergedCoverage.xml"
  paths:
    - "**/build/reports/jacoco/merged/html"
