apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
  labels:
    app: nginx

data:
  nginx.conf: |
    # OpenStack LoadBalancer는 L4(NodePort)로 트래픽을 전달한다.
    # Host 기반 분기는 LB가 아니라 Nginx에서 처리한다(Ingress 미사용).
    # TLS 종료가 LB에서 이뤄지면 443 → Nginx 80으로 HTTP가 전달된다.
    # TLS 종료를 Nginx에서 해야 한다면 listen 443 + 인증서 설정이 필요하다.
    # Ingress Controller는 사용하지 않는다(추가 도입 금지).
    # 서브도메인 추가 시 server 블록만 확장한다.
    # LB VIP 변경 시 jamie.kr DNS를 함께 갱신한다.
    events {}

    http {
      resolver kube-dns.kube-system.svc.cluster.local valid=10s;

      # grafana.jamie.kr 호스트 헤더를 기준으로 Grafana에 프록시한다.
      server {
        listen 80;
        server_name grafana.jamie.kr;

        location / {
          proxy_pass http://grafana.monitoring.svc.cluster.local:3000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

      # 기본 응답은 404로 반환한다. (jamie.kr 루트 사용 시 여기에 추가)
      server {
        listen 80 default_server;
        return 404;
      }
    }

    stream {
      resolver kube-dns.kube-system.svc.cluster.local valid=10s;

      # PostgreSQL은 TCP 라우팅만 가능하다(L4). Host 기반 분기 불가.
      server {
        listen 5432;
        proxy_pass postgres.infra.svc.cluster.local:5432;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
            - containerPort: 5432
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config
          configMap:
            name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    # OpenStack LB가 외부 VIP를 만들고 NodePort로 전달한다.
    # default-tls-container-ref가 설정되면 LB에서 TLS를 종료하고 443 → 80으로 전달한다.
    # L7 Host 기반 라우팅은 지원 여부와 무관하게 Nginx에서 처리한다.
    # Ingress Controller 도입 없이 Nginx ConfigMap만 유지한다.
    # LB VIP 변경 시 jamie.kr DNS 갱신을 선행한다.
    loadbalancer.openstack.org/flavor-id: adc12270-f56a-4ef1-bb00-429aad71ef6e
    loadbalancer.openstack.org/availability-zone: KR1-Zone1-LB
    loadbalancer.openstack.org/default-tls-container-ref: https://external.gabiacloud.com:9311/v1/secrets/88750a57-9a44-41d5-bc89-602ab2b131f8
    service.beta.kubernetes.io/openstack-internal-load-balancer: "false"
    loadbalancer.openstack.org/x-forwarded-for: "true"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: grafana
      port: 443
      protocol: TCP
      targetPort: 80
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
