apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.18.1
          env:
            # k -n infra get secret postgres-exporter -o jsonpath='{.data.data_source_name}' | base64 --decode
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-exporter
                  key: data_source_name
          ports:
            - containerPort: 9187

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: infra
spec:
  type: ClusterIP
  selector:
    app: postgres-exporter
  ports:
    - port: 9187
      targetPort: 9187
      protocol: TCP
